import React from 'react';
import { Epilogue } from 'next/font/google';

import ReduxProvider from '@/redux/ReduxProvider';

import StyledComponentsRegistry from './lib/AntdRegistry';
import { ConfigProvider } from 'antd';

import './globals.css';
// import '@/app/globals.css'; // this also worked

import theme from '@/utils/themeConfig';
// import theme from '../utils/themeConfig'; // this also worked

import UserLayout from '@/components/templates/Layout';

const font = Epilogue({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  const segment = children.props.childProp.segment;
  const path_except = ['__PAGE__', 'login', 'signup']; // 0: home page, 1: login page, 2: signup page are except using <UserLayout>
  const is_except = path_except.findIndex((el) => el === segment);

  // console.log(is_except); // user and message page value are -1

  return (
    <html lang="en">
      <body className={font.className}>
        <ReduxProvider>
          <StyledComponentsRegistry>
            <ConfigProvider theme={theme}>
              {is_except !== -1 ? children : <UserLayout>{children}</UserLayout>}
            </ConfigProvider>
          </StyledComponentsRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;

// notes:
// why we can't set the RootLayout to a client component (The root layout is a Server Component by default and can not be set to a Client Component --> https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required)
// we should separate the redux provider from RootLayout server component, because the redux provider need to set as a client component ('use client')
